name: Firebase Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: echo "::set-output name=dir::$(yarn cache dir)"
      id: yarn-cache-dir-path
      name: Get yarn cache directory path
    - uses: actions/cache@v2
      id: cache-yarn-cache
      name: Cache yarn cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: portal/node_modules
        key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-
    - run: yarn --frozen-lockfile
      if: |
        steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
      name: Install Dependencies
      working-directory: ${{env.working-dir}}
    - run: yarn build
      name: Build frontend
      working-directory: ${{env.working-dir}}
    - name: Deploy to Firebase
      run: npx firebase deploy --token=${{ secrets.FIREBASE_TOKEN }}
